### ISSUE TITLE
Unable to import `__version__`

### ISSUE THREAD

**Issue by jbcurtin** [spacetelescope/stwcs#113]
hello, the stack trace below highlights an error when importing `stwcs`. 
```
>>> import process_main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./process_main.py", line 31, in <module>
    from stwcs.wcsutil import headerlet, altwcs
  File "./wcsutil/headerlet.py", line 30, in <module>
    from stwcs.updatewcs import utils
  File "./stwcs/updatewcs/__init__.py", line 8, in <module>
    from .. import __version__
ImportError: cannot import name '__version__' from 'stwcs' (./stwcs/__init__.py)
```

The hangup happens when `__version__` isn't defined when its passed in the `try/catch` block
https://github.com/spacetelescope/stwcs/blob/master/stwcs/__init__.py#L26

It looks like this is intentional logic, but I'm uncertain how to move forward with limited error output. Which package should be installed?

**Comment by jhunkeler** [comment]
1. You should doing `pip install git+https://github.com/spacetelescope/stwcs#egg=stwcs` instead of trying to import the package from a direct source checkout. This works sometimes, but a lot of our programs tend to populate files during the build, or generate scripts in `[..]/bin`. So it's usually better/safer to install things into `site-packages`.

2. Replacing `pass` with `__version__ = 'unknown'` or `__version__ = '0.0.0'` would solve the relative import issue, but I suspect other problems may arise (missing dependencies, binaries, etc) anyway.

**Comment by jbcurtin** [comment]
Thanks for the feedback @jhunkeler, looks like the `egg` info is missing from our release packages. This is whats causing our edge case to fail when attempting to complete `1.` of your suggestions
