### ISSUE TITLE
function in distortion/utils.py does not check if attribute is None

### ISSUE THREAD

**Issue by molaes-stsci** [spacetelescope/stwcs#69]
In `distortion/utils.py`, the function `make_orthogonal_cd()`...

The following lines check if `wcs.idcscale` exists, but does not check if the value is set to `None`:

```
    124         # find pixel scale:
    125         if hasattr(wcs, 'idcscale'):
--> 126             scale = (wcs.idcscale) / 3600.  # HST pixel scale provided
    127         else:
    128             scale = np.sqrt(np.abs(det))  # find as sqrt(pixel area)
```

Proposed solution to add a conditional, similar to the following [wfc3 code](https://github.com/gbrammer/wfc3/blob/master/flt/model.py#L636):

```
    636     if hasattr(wcs, 'idcscale'):
    637         if wcs.idcscale is None:
    638                 wcs.idcscale = np.sqrt(np.sum(wcs.wcs.cd[0,:]**2))*3600.
    639     else:
    640         wcs.idcscale = np.sqrt(np.sum(wcs.wcs.cd[0,:]**2))*3600.
```

**Comment by philhodge** [comment]
Did you notice that the spacing is not correct in your example from wfc3?

**Comment by molaes-stsci** [comment]
> Did you notice that the spacing is not correct in your example from wfc3?

Whoops! No I did not. That is my fault- the code is pulled from GitHub and I wanted to include the line numbers. After I did so, I attempted to fix the spacing by hand.

Thank you for pointing that out. I have fixed the example.

**Comment by mcara** [comment]
I am somewhat against this change unless you can justify the need for it.  Specifically, under what circumstances do you encounter a situation when `idcscale` is `None` but you still want the code to run?

The reason that there is no check for `idcscale is None` is that non-HST images do not have this scale, while HST images _always_ have it **unless** users did not run `updatewcs()` on their images. However, it is a mistake to use this function unless `updatewcs()` was run first - otherwise the distortion model will not be applied correctly.

Thus, when used correctly, `idcscale` should never be `None`. Making this function quietly pass would hide serious problems with input images. I prefer the code to crash.

CC: @stsci-hack

**Comment by molaes-stsci** [comment]
> I am somewhat against this change unless you can justify the need for it. Specifically, under what circumstances do you encounter a situation when `idcscale` is `None` but you still want the code to run?
> 
> The reason that there is no check for `idcscale is None` is that non-HST images do not have this scale, while HST images _always_ have it and it always _should be_ non-`None` **unless** users did not run `updatewcs()` on their images. However, it is a mistake to use this function unless `updatewcs()` was run first - otherwise the distortion model will not be applied correctly and accordingly the CD matrix computed by this function will be incorrect (will not match intended scale and axis orientation).
> 
> Thus, when used correctly, `idcscale` should never be `None`. Making this function quietly pass would hide serious problems with input images. I prefer the code to crash.
> 
> CC: @stsci-hack

Ah, that makes sense. Thank you for clearing that up. The specific case was when applying AstroDrizzle to a raw dark current image that has had the (updated) wcs solution from a flat fielded image. I will find a different way to solve my issue.

Thank you for your help.
